### ISSUE TITLE
setup error, undefined state of freeathome integration

### ISSUE THREAD

**Issue by ckomorek59** [jheling/freeathome#294]
connection between controller and ha could not be established. Got 3 error protocols:

1.
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.freeathome
Quelle: config_entries.py:798
Integration: Busch Jaeger/ABB Free@Home (Dokumentation)
Erstmals aufgetreten: 22:02:42 (1 Vorkommnis)
Zuletzt protokolliert: 22:02:42

Error setting up entry 192.168.0.3 for freeathome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/freeathome/__init__.py", line 89, in async_setup_entry
    await sysap.find_devices()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 1041, in find_devices
    await self.xmpp.find_devices(self._use_room_names, self._switch_as_x)
          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_devices'

2.
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.freeathome.fah.settings
Quelle: custom_components/freeathome/fah/settings.py:28
Integration: Busch Jaeger/ABB Free@Home (Dokumentation)
Erstmals aufgetreten: 22:02:11 (2 Vorkommnisse)
Zuletzt protokolliert: 22:02:42

server not found

3.
Logger: homeassistant.config_entries
Quelle: config_entries.py:798
Erstmals aufgetreten: 22:02:11 (1 Vorkommnis)
Zuletzt protokolliert: 22:02:11

Error setting up entry 192.168.0.3 for freeathome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/freeathome/__init__.py", line 89, in async_setup_entry
    await sysap.find_devices()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 1041, in find_devices
    await self.xmpp.find_devices(self._use_room_names, self._switch_as_x)
          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_devices'Logger: homeassistant.config_entries
Quelle: config_entries.py:798
Erstmals aufgetreten: 22:02:11 (1 Vorkommnis)
Zuletzt protokolliert: 22:02:11

Error setting up entry 192.168.0.3 for freeathome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/freeathome/__init__.py", line 89, in async_setup_entry
    await sysap.find_devices()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 1041, in find_devices
    await self.xmpp.find_devices(self._use_room_names, self._switch_as_x)
          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_devices'

No idea, how this happed, please be so kind and advise, thanks in advance!!!!!!

**Comment by ckomorek59** [comment]
after updating manifest from 1.0.8 to 1.0.9: situation unchanged, errors still existing

**Comment by ckomorek59** [comment]
Home Assistant Core
Keine Probleme für Suchbegriff „freeathome“ gefunden
2026-07-24 22:44:10.194 ERROR (MainThread) [custom_components.freeathome.fah.settings] server not found
2026-07-24 22:44:10.195 ERROR (MainThread) [custom_components.freeathome] Error setting up entry 192.168.0.3 for freeathome
  File "/config/custom_components/freeathome/__init__.py", line 88, in async_setup_entry
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 1041, in find_devices

**Comment by ckomorek59** [comment]
Sorry, my failure, freeathome access point was hanging.
