### ISSUE TITLE
Problem with Update Core 2025.1.0

### ISSUE THREAD

**Issue by jws75** [jheling/freeathome#220]
With the latest update to core 2025.1.0 of Home Assistant it has stopped working, has this happened to anyone else?

I rolled back to 2024.12.5 and with this Version it works fine again.

**Comment by GerdJenn** [comment]
Hi, same problem for me with today's update to 2025.1.0. 
![Screenshot_20250105_195324_Home Assistant](https://github.com/user-attachments/assets/fb5877d9-2ddf-4750-8e6b-d4d6a65c1f44)

**Comment by rbierings** [comment]
same problem here. 
Since 2025.1.0 I can no longer control the free@home devices via Home Assistant. Controling stuff via the free@home app still works without any problems.

**Comment by AlexOB2612** [comment]
Same here, downgrade back to 2024.12.5 fixed it.

**Comment by MrDiSi** [comment]
same here...

**Comment by PaegelowM** [comment]
Hello,
not for me, it still works fine so far except for the issue i posted before.

https://github.com/jheling/freeathome/issues/219
https://github.com/jheling/freeathome/issues/218

**Comment by jheling** [comment]
My main Home Assistant with this integration is running in Proxmox.  My test Home Assistant version with this integration is on a raspberry pi 3.  Both are upgraded to 2025.1.0 and have no problems. So both are running on Home Assistant OS.  On what systems are you running Home Assistant?

**Comment by MrDiSi** [comment]
System is complete Up to Date an ist running HA OS ob Raspi4

Seems some Elements are reconized but Not the controls for covers

jheling ***@***.***> schrieb am Mo., 6. Jan. 2025, 19:21:

**Comment by rbierings** [comment]
mine is also on a Raspberry Pi4 with HA OS 2025.1.0

**Comment by MrDiSi** [comment]
![Screenshot_2025-01-06-19-29-02-963_io homeassistant companion android](https://github.com/user-attachments/assets/dc17ac30-f424-4e77-9706-3c04d24eb137)

**Comment by jheling** [comment]
Do you see any errors in the Home Assistant Log?

**Comment by MrDiSi** [comment]
Yes 

``Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: homeassistant
Quelle: custom_components/freeathome/sensor.py:5
Integration: Busch Jaeger/ABB Free@Home (Dokumentation)
Erstmals aufgetreten: 5. Januar 2025 um 16:19:42 (1 Vorkommnisse)
Zuletzt protokolliert: 5. Januar 2025 um 16:19:42

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2349, in async_forward_entry_setup
    result = await self._async_forward_entry_setup(entry, domain, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2380, in _async_forward_entry_setup
    await integration.async_get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1108, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1185, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1098, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/freeathome/sensor.py", line 5, in <module>
    from homeassistant.const import (
    ...<2 lines>...
        )
ImportError: cannot import name 'SPEED_KILOMETERS_PER_HOUR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)


Or 

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: slixmpp.stringprep
Quelle: custom_components/freeathome/fah/pfreeathome.py:12
Integration: Busch Jaeger/ABB Free@Home (Dokumentation)
Erstmals aufgetreten: 5. Januar 2025 um 16:19:37 (1 Vorkommnisse)
Zuletzt protokolliert: 5. Januar 2025 um 16:19:37

Using slower stringprep, consider compiling the faster cython/libidn one.

**Comment by jheling** [comment]
It looks like you have to replace the sources of this integration in your custom_components directory.  The import error  is an indication of an old source .  The name SPEED_KILOMETERS_PER_HOUR has been replaced by UnitOfSpeed.KILOMETERS_PER_HOUR in a pull request about 9 months ago.

**Comment by rbierings** [comment]
I got this in my log:

025-01-05 20:00:12.613 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'freeathome' calls async_forward_entry_setup for integration, freeathome with title: 192.168.188.70 and entry_id: 161ab8ef277154f24b6f79a36765b178, which is deprecated, await async_forward_entry_setups instead at custom_components/freeathome/__init__.py, line 80: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please report it to the author of the 'freeathome' custom integration

**Comment by MrDiSi** [comment]
Some Here: i'v integrate by ip4 Adress an HA dedect ***@***.*** also as an IP
V6 device. Ignore This device always

rbierings ***@***.***> schrieb am Mo., 6. Jan. 2025, 20:28:

**Comment by jws75** [comment]
> It looks like you have to replace the sources of this integration in your custom_components directory. The import error is an indication of an old source . The name SPEED_KILOMETERS_PER_HOUR has been replaced by UnitOfSpeed.KILOMETERS_PER_HOUR in a pull request about 9 months ago.

Can you explain what you mean by "replace the sorces" in a bit more detail? Do the files in the custom_components path simply have to be overwritten? Certainly not all of them, right?

**Comment by jheling** [comment]
@jws75 Yes, overwriting all the sources in the freeathome directory and below. And then a full reset of home assistant.  At the code of this integration you can download the whole source tree as a zip file through the green code button.

**Comment by domi8671** [comment]
I was in the same situation a while ago because I had installed F@H manually, as you probably did. I added the repository in HACS and installed it again from there. I hadn't changed the previous installation. Then I restarted HA completely and it worked.

**Comment by rbierings** [comment]
The new 2025.1.1 update fixed it again

**Comment by MrDiSi** [comment]
Not for me

rbierings ***@***.***> schrieb am Di., 7. Jan. 2025, 18:07:

**Comment by MrDiSi** [comment]
Replace the source Files solved it Here. Thanks a lot

Dirk Silbermann ***@***.***> schrieb am Di., 7. Jan. 2025, 18:08:

**Comment by reeeeevls** [comment]
Does not work under 2025.1.0 or 2025.1.1 
Complete entitys are not available. Rollback to 2024 fixed it.

**Comment by reeeeevls** [comment]
Does not work under 2025.1.0 or 2025.1.1 
Complete entitys are not available. Rollback to 2024 fixed it.

**Comment by RichardvanGestel** [comment]
Update to 2025.1 and replacing the (free@home) source Files solved it Here.
Thanx!

**Comment by Darkscale80** [comment]
Hello All,
i can confirm, after **replace all files of "custom_components/freeathome" by actual downloaded version**. This will be fix that isste.

Nevertheless, Why freeathome seems have no update funtionality? When I try to remember freeathome never was listed as "Update available". But that is another point.

**Comment by jws75** [comment]
> > It looks like you have to replace the sources of this integration in your custom_components directory. The import error is an indication of an old source . The name SPEED_KILOMETERS_PER_HOUR has been replaced by UnitOfSpeed.KILOMETERS_PER_HOUR in a pull request about 9 months ago.
> 
> Hei jheling, Can you explain what you mean by "replace the sorces" in a bit more detail? Do the files in the custom_components path simply have to be overwritten? Certainly not all of them, right?
> 
> (my system is also on a Raspberry Pi4 with HA OS 2025.1.0)
> 
> I don't have any log because of the rollback.


@jheling  Thank you very much!

The source update helped. It was hard work because I had to set up f@h again. Now everything works again. Hopefully we won't have to do this more often.

**Comment by tsgoff** [comment]
update the source or switch to HACS fixed it. However, you can no longer start an action when a roller blind is moving. You must therefore wait until the roller blind has reached the respective end position. The percentage opening is also no longer displayed in HA.

**Comment by reeeeevls** [comment]
Okay. After replacing the files I could control my blinds again.  
But there is another problem: the entities from the weather station are not updated. 
I have to reload the whole Integration to get them updated.

**Comment by solopa** [comment]
I wasn't sure about opening a new issue, but although I haven't tested to downgrade HA, I'm pretty sure this is also related to the 2025.1 update.

I have 4 dimmers installed that worked very well with this integration (thanks for your work!). They have a pretty old firmware and I don't really want to update, so I can't use the official app.

Since the update the status of each light doesn't update when pressed. And it shows a very strange behaviour. For example:

1. Initial state: light off, entity shows state off.
2. I switch it on directly in the controls of the device through the freeathome integration.
3. The light turns on and stays on. However, the switch control in the freeathome integration goes to on for like a second and then returns to off. Now the light is on and the "integration switch" is at off. The state of the entity is off, as if the integration correctly sent the message to the sysap (switching the light on) but never received an ack (thinking it is off).
4. Now, if I press again the switch through HA (repeating the point number 2) the light turns off, but the HA switch has the same behaviour (goes to on for like a second and then returns to off).
5. If I press again the switch, the light doesn't react (it stays off and doesn't change when I press the switch in HA). I can change this if I keep tapping the switch (maybe it sends a lot of message to the sysap and one of them is the correct one?).

The state of the entity doesn't reflect the state of the light if I turn it on or off using the physical switch either. It looks like something has changed in HA that broke the communication between the sysap and freeathome.

I've tried to completely delete the source and reinstall the integration from scratch after adding the repository to HACS. I'm using latest HA and latest freeathome (1.0.0). After setting up again the devices the problem still remains.

I've tried to use the freeathome_monitor service, but it always outputs a zero bytes long file.

Enabling the debug in the integration I've found this (similar to other posts in this thread, but it's a message about SSL problems): [https://pastebin.com/vmUA7Hgy](url)

Is there anything I can do so you can help me? ;) This integration is very important to me, to the point that, if needed, I will downgrade HA.

Thanks in advance!

**Comment by solopa** [comment]
Maybe not related, but the update to Python 3.13 could be the culprit (for example: [a problem with SSL and Python 3.13](https://stackoverflow.com/questions/79123649/does-python-3-13-ignore-ssl-cert-file-environment-variable-by-design)).

**Comment by domi8671** [comment]
I have the latest version of the integration and HA, the lights work for me, both switch and binary sensor stay on. Might be a local or an installation problem?

**Comment by solopa** [comment]
Well, the problem was almost certainly in my installation. Now I have fixed it. However, just in case (although it was probably unrelated), I downgraded HA.

What I did was:
- Downgrade to 2024.12.5 (I don't think this step was important, but just to be sure).
- Shut down Home Assistant.
- Turn off my sysap. In my case, this means turning off the mains. I did it yesterday, but this time I waited a few minutes.
- Boot up my sysap—everything works properly through the web.
- Boot up Home Assistant—everything works there too.
- Update Home Assistant to 2025.1.4—it still works!

I think the most important thing I did this time was waiting a few minutes while the mains were off. Sorry for the false alarm!

**Comment by solopa** [comment]
I celebrated too soon. A few hours later, I'm facing the same issue again. In the log, I see the following message:
`2025-02-02 10:41:30.964 WARNING (MainThread) [custom_components.freeathome.fah.pfreeathome] Connection with SysAP lost`

It might be a problem with my setup, but as soon as I can, I'll switch back to version 2024.12.5, cut the power to my house, and wait to see what happens. If there's anything noteworthy, I'll share it here. In the meantime, I'll keep an eye on GitHub to see if there are any updates on the integration.
